{% set name = "aiida-pythonjob" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida_pythonjob-{{ version }}.tar.gz
  sha256: 6d39ec88a3fd0264552a2744fa1830793f68b7e935d024f5d2461f46851dcd84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - node-graph >=0.3.9
    - ase
    - python >={{ python_min }}
    - aiida-core >=2.3,<3
    - cloudpickle
    - voluptuous

test:
  commands:
    - pip check
    - verdi presto --profile-name test
    - python -c "import aiida_pythonjob"
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Run Python functions on a remote computer.
  home: https://github.com/aiidateam/aiida-pythonjob
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
