{% set name = "aiida-pythonjob" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida_pythonjob-{{ version }}.tar.gz
  sha256: 4fff8c654496eb5d7eeeb33f23748ea99c3024b3687fd315c494d34a5db795fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - node-graph >=0.2.23,<0.3.dev0
    - ase
    - python >={{ python_min }}
    - aiida-core >=2.3,<3
    - cloudpickle
    - voluptuous

test:
  imports:
    - aiida_pythonjob
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Run Python functions on a remote computer.
  home: https://github.com/aiidateam/aiida-pythonjob
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
