{% set name = "aiida-pythonjob" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida_pythonjob-{{ version }}.tar.gz
  sha256: 8bb43eacb7ec346c5e32bfbccbd6b9c56bf0342181e59b69581734dd4e0b0196

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - node-graph >=0.6.0,<0.7.dev0
    - ase
    - python >={{ python_min }}
    - aiida-core >=2.7.1,<3
    - cloudpickle
    - voluptuous
    - plumpy <=0.25.0

test:
  commands:
    - pip check
    - verdi presto --profile-name test
    - python -c "import aiida_pythonjob"
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Run Python functions on a remote computer.
  home: https://github.com/aiidateam/aiida-pythonjob
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
