{% set name = "aiida-pythonjob" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida_pythonjob-{{ version }}.tar.gz
  sha256: 5e63120bce31a694386a632ccaaa5d85cad548fb7e3f0d6327ecfa1f718db03f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - ase
    - python >={{ python_min }}
    - aiida-core >=2.3,<3
    - cloudpickle
    - voluptuous

test:
  imports:
    - aiida_pythonjob
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Run Python functions on a remote computer.
  home: https://github.com/aiidateam/aiida-pythonjob
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
